baseURL: "https://jooncode.com"
languageCode: "en-us"
title: "Joon Profile"
theme: profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog Photos
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Joon Career"
  description: Information about Joon 
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/favicon/favicon.ico" # Logo for the brand | default is the favicon variable
    #showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "00N" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "HwiJoon Lee."
    subtitle: "Backend developer"
    content: "A passionate 4th year Computer Science Student"
    image: /me/AI.jpg
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Halfgear
        - icon: fab fa-instagram
          url: https://www.instagram.com/joonlh/
        - icon: fab fa-linkedin
          url: "https://www.linkedin.com/in/lee-hwi-joon-3004401a4"
        - icon: fab fa-discord
          url: "https://discordapp.com/users/287802139781103616"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/me/selfie.JPG"
    content: |-
      I have a true passion for technology and studying game industry. 
      I switched my major from chemistry to computer science, and it has been one of the best decisions I've ever made.
      Although I may have started my journey a little later than some of my peers, 
      I've discovered all the amazing things this field has to offer.
      
    skills:
      enable: true
      title: "Few technologies I've been working with:"
      items:
        - "Java"
        - "C++"
        - "Object Oriented Design"
        - "Docker"
        - "PostgresSQL"
        - "Chemistry"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Discord Service Developer"
        company: "PS Analytics Co"
        companyUrl: "https://lol.ps"
        date: "Dec 2022 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Developed a bot structured with Node.js, Postgresql, TypeORM.
          - Visit https://jooncode.com/blogs/class/nestdiscordbot/ for more details
          - Constructed the bot and PostgreSQL in a container with docker-compose.
          
      - job: "Object Oriented Design TA"
        company: "Northeastern University"
        companyUrl: "https://www.khoury.northeastern.edu"
        date: "Jan 2023 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Facilitated student understanding of SOLID principles. 
          - Instructed students on various object-oriented design strategies.

      - job: "CBRN Specialist"
        company: "Republic of Korea Army"
        companyUrl: "https://en.wikipedia.org/wiki/Republic_of_Korea_Army"
        date: "Sep 2020 - Mar 2022"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Operated chemical reconnaissance equipment.
          - Hired as a translator for the ROK-US Combined Forces Command.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Northeastern University"
          url: "https://www.northeastern.edu"
        date: "2018 - 2024"
        GPA: "3.59 out of 4.0"
        content: |-
          4th year student. Currently rushing through all Computer Science courses due to late major change.

      - title: "High School"
        school:
          name: "Subiaco Academy"
          url: "https://www.subiacoacademy.us"
        GPA: "4.0 out of 4.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
    

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Image Processor
        content: A basic Image Processor that supports Graphic User Interface. Code available upon request.
        image: /projects/ImageGUI.png
        badges:
          - "Java"
          - "JavaSwing"
          - "Object Oriented Design"

      - title: NestDiscordBot
        content: Currently learning and developing with PostgresSQL and docker-compose.,
        image: /projects/NoTrollz.jpg
        badges:
          - "Nest"
          - "TypeScript"
          - "Docker"
        links:
          - icon: fab fa-github
            url: https://github.com/Halfgear/NestDiscordBot

  #Contact
  contact:
    enable: true
    #title: ""
    content: My email is always open. Hit me up whenever!
    email: megalojoon@gmail.com
    btnName: Click to mail me!
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"