baseURL: "https://jooncode.com"
languageCode: "en-us"
title: "Joon Career"
theme: profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-6Z99Z4T0L0

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog Photos
    #   url: /gallery
    #   weight: 2
    # Dropdown menu
    - identifier: blog
      title: interests
      name: Interests
      url: /blogs
      # parent: dropdown
      weight: 1
    - identifier: post
      title: Post
      name: Post
      url: /study
      # parent: dropdown
      weight: 2

params:
  title: "Joon Career"
  description: Information about Joon 
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  #cloudinary_cloud_name: "dpkevwens"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor: 
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/favicon/favicon.ico" # Logo for the brand | default is the favicon variable
    #showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "00N" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "HwiJoon Lee"
    subtitle: "Backend developer (Java/Nodejs)"
    content: "Passionate Computer Science Student"
    image: /me/AI.jpg

    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://docs.google.com/document/d/1aIfynNS2C6CA2gZL8I3l_RjVEDyIFYHr/edit?usp=sharing&ouid=118185476807190519222&rtpof=true&sd=true"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Halfgear
        - icon: fab fa-instagram
          url: https://www.instagram.com/joonlh/
        - icon: fab fa-linkedin
          url: "https://www.linkedin.com/in/lee-hwi-joon-3004401a4"
        - icon: fab fa-discord
          url: "https://discordapp.com/users/287802139781103616"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/me/me.jpg"
    content: |-
      I switched my major from chemistry to computer science, and it has been one of the best decisions I've ever made.
      Although I may have started my journey a little later than some of my peers, 
      I've discovered all the amazing things this field has to offer.

      I am currently looking for co-op or internship for fall 2023.
      
    skills:
      enable: true
      title: "Here are a few technologies I've been working with:"
      items:
        - "Java"
        - "C++"
        - "TypeScript"
        - "Docker"
        - "PostgresSQL"
        - "Nodejs"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Object Oriented Design TA"
        company: "Northeastern University"
        companyUrl: "https://www.khoury.northeastern.edu"
        date: "Jan 2023 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Facilitated student's understanding of readable and maintainable code 
          - Instructed on various object-oriented design strategies with examples.
          - Reviewed student code submissions to provide detailed feedback

      - job: "Discord Service Developer"
        company: "PS Analytics"
        companyUrl: "https://lol.ps"
        date: "Dec 2022 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Implemented a custom bot for a large-scale community gaming server
          - Automated user registration and role management to improve team efficiency
          - Collaborated with other developers to build an extendable functionality

      - job: "CBRN Specialist"
        company: "Korea Army"
        companyUrl: "https://en.wikipedia.org/wiki/Republic_of_Korea_Army"
        date: "Sep 2020 - Mar 2022"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Operated chemical reconnaissance equipment.
          - Participated in a national wide operation for the ROK-US Combined Forces Command.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Northeastern University"
          url: "https://www.northeastern.edu"
        date: "Aug 2018 - Dec 2024"
        GPA: "3.59 out of 4.0"
        content: |-
          4th year student. Two gap years for Military service.
  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
    

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Image Processor
        content: Image Processor that supports Graphic User Interface. Code available upon request.
        image: /projects/ImageGUI.png
        badges:
          - "Java"
          - "JavaSwing"
          - "Object Oriented Design"

      - title: NestDiscordBot
        content: Bot structured with Nestjs Framework and TypeScript. Deployed in docker container with PostgreSQL database.
        image: /projects/docker+postgresql.jpeg
        badges:
          - "Nest"
          - "TypeScript"
          - "Docker"
        links:
          - icon: fab fa-github
            url: https://github.com/Halfgear/NestDiscordBot
          - icon: fab fa-markdown
            url: https://jooncode.com/study/nestdiscordbot/

  #Contact
  contact:
    enable: true
    #title: ""
    content: My email is always open. Hit me up whenever!
    email: megalojoon@gmail.com
    btnName: Click to Email me!
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: xayzpnnv # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "study"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"